### ISSUE TITLE
Plenary document now missing ToC

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-un#1]
The entire ToC is gone. Urgent fix needed.

**Comment by opoudjis** [comment]
The plenary was ALWAYS missing a ToC, because the sample plenary document was missing a ToC. I am putting a ToC in, but until UNECE can produce actual documentation of what goes into their documents, we should not be guessing only to be disproven.

**Comment by ronaldtse** [comment]
Somehow I didn’t get the notification for this... glad I checked!

The HTML version should have a ToC nonetheless, it looks strange without it.

**Comment by ronaldtse** [comment]
And there used to be a ToC, in my poorly reliable memory.

**Comment by opoudjis** [comment]
... I see that some of the Plenary papers have a ToC, and some don't.

I also see that some Plenary papers have a full title page, and some don't, and there are limits to how much foolishness I will support.

The "Intro" page is currently suppressed for plenary papers, because there was no stated need for it from the information given to me. Given this, I will need to specify whether a table of contents is needed as a document option.

**Comment by opoudjis** [comment]
The alternative is to always insert a ToC in both Word and HTML, which would be the only sensible thing to do. The problem is that that means ToCs for squibs like http://www.unece.org/fileadmin/DAM/cefact/cf_plenary/plenary15/ECE_TRADE_C_CEFACT_2015_3E_matters_arising.pdf , or http://www.unece.org/fileadmin/DAM/cefact/cf_plenary/plenary15/ECE_TRADE_C_CEFACT_2015_9E_Corr1.pdf . But it is absurd to craft a PDF for a one-line corrigendum to begin with; and if it is, it is no more absurd to give it a full ToC.

Not proceeding until I have actual requirements, on whether to put ToC in all Plenary papers or only some, and whether to treat Word and HTML differently.

**Comment by ronaldtse** [comment]
The full guide is here http://dd.dgacm.org/editorialmanual/

**Comment by ronaldtse** [comment]
I don’t see why a PDF document for a one-line corrigendum is a problem; that’s the nature of a corrigendum. The absurdity is wanting a ToC for such case, since the full content is already available on the first page.

**Comment by opoudjis** [comment]
Table of contents will always appear in HTML documents.

Table of contents will only appear in Word documents if the `:toc:` document attribute is present—which is consistent with default Asciidoctor behaviour.

Also debugged the occurrence of page breaks for foreword, introduction, abstract: these were not being stripped if any of these were being moved around in the document (e.g. the abstract into the summary box).

**Comment by ronaldtse** [comment]
The ToC behavior of HTML and Word being inconsistent is strange. Please make sure we document that somewhere properly (in a section where it talks about features?)

**Comment by opoudjis** [comment]
> The ToC behavior of HTML and Word being inconsistent is strange. 

It was your request :)
