### ISSUE TITLE
Sections get numbered as if they were paragraphs

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-un#8]
If no paragraph or subsection is present at the beginning of the section, this one gets numbered as if it was a paragraph.

![Capture1](https://user-images.githubusercontent.com/33627611/71391114-3d039f80-25d9-11ea-9aeb-a5bf9fa1d209.JPG)

Sample: 
[section-issue.zip](https://github.com/metanorma/mn-samples-un/files/3997072/section-issue.zip)

**Comment by ronaldtse** [comment]
Thanks @manuel489 ! This is interesting — I did notice this when I assigned the task. The “provisional agenda” and “meeting agendas documents are special (maybe a separate doctype) because their numbering structure is different. 

For simplicity and understanding I propose a new doctype. Thoughts @opoudjis?

**Comment by opoudjis** [comment]
This also impacts on the other issue Manuel found, that paragraphs were being numbered.

What's really happening is that we developed the two classes of document that I was given, and this is a distinct class of document.

Yes, we can create a new class of document, but given the large number of idiosyncracies in UNECE documents, I would want authoritative analysis of document requirements, rather than me trying to work it out from scratch; and I would much prefer to delegate that work. As should be painfully obvious from how long it is taking me to respond to these tickets, I simply don't have the time to do it.

@ronaldtse, we will need to resume discussion with UNECE staff; the answers will have to come from them. I acknowledge you'd already identified these issues in your email to them on 7 December, about these documents.

**Comment by ronaldtse** [comment]
> we will need to resume discussion with UNECE staff; the answers will have to come from them. I acknowledge you'd already identified these issues in your email to them on 7 December, about these documents.

It seems that there are no definitive answers from UNECE staff, I feel that it's a lot of "watch and learn" and all editors eventually end up with something different.

Maybe what we should do is to create a "Style Guide" for UNECE.

**Comment by manuelfuenmayor** [comment]
Excuse me guys (@ronaldtse  and @opoudjis), but I believe this issue has nothing to do with implementing a new doctype, but with fixing a bug. 

I'm going to explain myself using a doc I converted weeks ago as example: https://github.com/metanorma/mn-samples-un/pull/10

You see, in that doc, there is a section called `Provisional timetable`. So, taking a relevant capture  of both the original doc and metanorma output for comparison purposes, we have:

![capture6](https://user-images.githubusercontent.com/33627611/72600746-9ade8b00-38ea-11ea-92a2-af4376a4d87a.JPG)

Notice that, the numbering of `Provisional timetable` section in both docs are different. In metanorma output, the number `48` corresponds to a paragraph number (notice the ascending order of the paragraphs) . So, for some reason, this happens because there is no text element immediately below the `Provisional timetable` section, only a table. 
Now, if I put some Lorem Ipsum text below it, then:

![capture7](https://user-images.githubusercontent.com/33627611/72601328-8fd82a80-38eb-11ea-8767-f6404ce38c0e.JPG)

the problem is solved. 

You can reproduce this bug using the sample file I attached above in the description of this issue. Just add some text below the sections and notice how the numbering style changes to Roman numerals.
(Sorry for clearing this up so late.)

**Comment by opoudjis** [comment]
Paragraphs in UNECE are detected as terminal clauses, those that have no clause children. And metanorma-unece helpfully wraps any paragraphs in clause wrappers, so that they can be terminal clauses.

A section with no content will be treated as a terminal clause. That's slightly pathological.

More importantly though, a clause containing just a table with not contain any subclauses, since tables are not numbered; but the gem incorrectly concludes that the section is a paragraph. The condition instead needs to be refined. A paragraph needs to be a clause that contains no subclauses, but that DOES contain `<p>`.
