### ISSUE TITLE
Text footnote referenced in the doc title doesn't show up

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-samples-un#9]
The text from a footnote directly referenced in the title does not appear.

![Capture2](https://user-images.githubusercontent.com/33627611/71391364-39bce380-25da-11ea-90dc-5eb779afc9f6.JPG)

Sample: 
[title-footnote-issue.zip](https://github.com/metanorma/mn-samples-un/files/3997084/title-footnote-issue.zip)

**Comment by ronaldtse** [comment]
Thanks @manuel489 for discovering this. I think it is odd to have a footnote in that title — a title ought to be independent and in plain text. 

The footnote texts in the said document serve the purpose of “notes” and should be encoded as such in the content. So let’s move those from the title to a new “cover page preface” section.  

@opoudjis thoughts?

**Comment by opoudjis** [comment]
Footnotes in titles are going to be asking for trouble at the best of times, especially given all the manipulation that happens in cover pages. Titles as document attributes are simply not going to be checked for footnotes; the whole premise of document attributes is that they are not subject to any postprocessing — that's why they're used to sidestep Asciidoctor substitutions. So such footnotes will not work, and getting them to work would be so involved as to be counterproductive.

I will document this as a gotcha in metanorma.com.
